version: "3"

services:
  wppconnect:
    container_name: wpp-server
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ./config.ts:/usr/src/wpp-server/config.ts
      - ./userDataDir:/usr/src/wpp-server/userDataDir  # cambio clave: coincide con customUserDataDir
    ports:
      - "21465:21465"
